name: minimal pipeline with R, Google Spreadsheets, and Poorman

# on:
#   schedule:
#     - cron: '0 2 */3 * *'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pipeline-run:
    name: "Job: full pipeline run"
    runs-on: ubuntu-latest
    container:
      image: docker://nathaneastwood/poorman
    env:
      SHEETID: ${{ secrets.SHEETID }}
      TOKEN: ${{ secrets.TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install sys libs
        run: |
          apt-get update && apt-get install libcurl4-openssl-dev libssl-dev -qq
      # - name: "Run R"
      #   run: |
      #       R -e 'install.packages("googlesheets4", lib = "/usr/local/lib/R/site-library")'
      #       r R/00-main.R
      #       # artifacts:
